import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getCurrentUser } from "../auth";
import { signOut } from "./functions/auth";
import LoginStatus from "../components/LoginStatus";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-amber-700 p-2">
          <h1 className="text-2xl font-bold">Root Layout</h1>

          <Suspense fallback={<p>Loading...</p>}>
            <LoginStatus />
          </Suspense>

          

          {children}
        </div>
      </body>
    </html>
  );
}
